language: java

os:
  - linux

jdk:
  - oraclejdk8

install:
  - git submodule update --remote
  - mvn install dependency:go-offline -Pskip-formatter -DskipTests=true -fn -q

script:
  - mvn clean install -Pci -B
